<?php
/**
 * BillingAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * BillingAccountTest Class Doc Comment
 *
 * @category    Class
 * @description BillingAccount
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BillingAccountTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BillingAccount"
     */
    public function testBillingAccount()
    {
    }

    /**
     * Test attribute "billing_threshold"
     */
    public function testPropertyBillingThreshold()
    {
    }

    /**
     * Test attribute "create_by"
     */
    public function testPropertyCreateBy()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "demand_enabled"
     */
    public function testPropertyDemandEnabled()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "invoice_time"
     */
    public function testPropertyInvoiceTime()
    {
    }

    /**
     * Test attribute "monthly_spend"
     */
    public function testPropertyMonthlySpend()
    {
    }

    /**
     * Test attribute "stripe_ref"
     */
    public function testPropertyStripeRef()
    {
    }

    /**
     * Test attribute "supply_enabled"
     */
    public function testPropertySupplyEnabled()
    {
    }

    /**
     * Test attribute "tax_ids"
     */
    public function testPropertyTaxIds()
    {
    }
}
