<?php
/**
 * DataCenterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DataCenterTest Class Doc Comment
 *
 * @category    Class
 * @description DataCenter
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DataCenterTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DataCenter"
     */
    public function testDataCenter()
    {
    }

    /**
     * Test attribute "create_by"
     */
    public function testPropertyCreateBy()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "lng_lat"
     */
    public function testPropertyLngLat()
    {
    }

    /**
     * Test attribute "one_frontend_id"
     */
    public function testPropertyOneFrontendId()
    {
    }

    /**
     * Test attribute "region_id"
     */
    public function testPropertyRegionId()
    {
    }

    /**
     * Test attribute "renewable_energy"
     */
    public function testPropertyRenewableEnergy()
    {
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
    }
}
