<?php
/**
 * DiskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DiskTest Class Doc Comment
 *
 * @category    Class
 * @description Disk
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DiskTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Disk"
     */
    public function testDisk()
    {
    }

    /**
     * Test attribute "create_time"
     */
    public function testPropertyCreateTime()
    {
    }

    /**
     * Test attribute "data_center_id"
     */
    public function testPropertyDataCenterId()
    {
    }

    /**
     * Test attribute "disk_state"
     */
    public function testPropertyDiskState()
    {
    }

    /**
     * Test attribute "disk_type"
     */
    public function testPropertyDiskType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "private_image_id"
     */
    public function testPropertyPrivateImageId()
    {
    }

    /**
     * Test attribute "project_id"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "public_image_id"
     */
    public function testPropertyPublicImageId()
    {
    }

    /**
     * Test attribute "size_gib"
     */
    public function testPropertySizeGib()
    {
    }

    /**
     * Test attribute "storage_class"
     */
    public function testPropertyStorageClass()
    {
    }

    /**
     * Test attribute "vm_id"
     */
    public function testPropertyVmId()
    {
    }
}
