<?php
/**
 * GetObjectStorageSessionKeyResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * GetObjectStorageSessionKeyResponseTest Class Doc Comment
 *
 * @category    Class
 * @description GetObjectStorageSessionKeyResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetObjectStorageSessionKeyResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetObjectStorageSessionKeyResponse"
     */
    public function testGetObjectStorageSessionKeyResponse()
    {
    }

    /**
     * Test attribute "access_key"
     */
    public function testPropertyAccessKey()
    {
    }

    /**
     * Test attribute "endpoint"
     */
    public function testPropertyEndpoint()
    {
    }

    /**
     * Test attribute "secret_key"
     */
    public function testPropertySecretKey()
    {
    }

    /**
     * Test attribute "session_name"
     */
    public function testPropertySessionName()
    {
    }

    /**
     * Test attribute "session_token"
     */
    public function testPropertySessionToken()
    {
    }
}
