<?php
/**
 * ProjectIdVmBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProjectIdVmBodyTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectIdVmBody
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectIdVmBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProjectIdVmBody"
     */
    public function testProjectIdVmBody()
    {
    }

    /**
     * Test attribute "boot_disk"
     */
    public function testPropertyBootDisk()
    {
    }

    /**
     * Test attribute "boot_disk_image_id"
     */
    public function testPropertyBootDiskImageId()
    {
    }

    /**
     * Test attribute "cpu_model"
     */
    public function testPropertyCpuModel()
    {
    }

    /**
     * Test attribute "custom_ssh_keys"
     */
    public function testPropertyCustomSshKeys()
    {
    }

    /**
     * Test attribute "data_center_id"
     */
    public function testPropertyDataCenterId()
    {
    }

    /**
     * Test attribute "gpu_model"
     */
    public function testPropertyGpuModel()
    {
    }

    /**
     * Test attribute "gpus"
     */
    public function testPropertyGpus()
    {
    }

    /**
     * Test attribute "machine_type"
     */
    public function testPropertyMachineType()
    {
    }

    /**
     * Test attribute "max_price_hr"
     */
    public function testPropertyMaxPriceHr()
    {
    }

    /**
     * Test attribute "memory_gib"
     */
    public function testPropertyMemoryGib()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "nics"
     */
    public function testPropertyNics()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "security_group_ids"
     */
    public function testPropertySecurityGroupIds()
    {
    }

    /**
     * Test attribute "ssh_key_source"
     */
    public function testPropertySshKeySource()
    {
    }

    /**
     * Test attribute "start_script"
     */
    public function testPropertyStartScript()
    {
    }

    /**
     * Test attribute "storage_disk_ids"
     */
    public function testPropertyStorageDiskIds()
    {
    }

    /**
     * Test attribute "vcpus"
     */
    public function testPropertyVcpus()
    {
    }

    /**
     * Test attribute "vm_id"
     */
    public function testPropertyVmId()
    {
    }
}
