<?php
/**
 * VMDataCenterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * VMDataCenterTest Class Doc Comment
 *
 * @category    Class
 * @description VMDataCenter
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VMDataCenterTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VMDataCenter"
     */
    public function testVMDataCenter()
    {
    }

    /**
     * Test attribute "disk_pool_pricing"
     */
    public function testPropertyDiskPoolPricing()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "ipv4_price_hr"
     */
    public function testPropertyIpv4PriceHr()
    {
    }

    /**
     * Test attribute "network_pricing"
     */
    public function testPropertyNetworkPricing()
    {
    }

    /**
     * Test attribute "region_id"
     */
    public function testPropertyRegionId()
    {
    }

    /**
     * Test attribute "renewable_energy"
     */
    public function testPropertyRenewableEnergy()
    {
    }

    /**
     * Test attribute "supplier_name"
     */
    public function testPropertySupplierName()
    {
    }
}
