<?php
/**
 * VMTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * VMTest Class Doc Comment
 *
 * @category    Class
 * @description VM
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VMTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VM"
     */
    public function testVM()
    {
    }

    /**
     * Test attribute "active_state"
     */
    public function testPropertyActiveState()
    {
    }

    /**
     * Test attribute "boot_disk"
     */
    public function testPropertyBootDisk()
    {
    }

    /**
     * Test attribute "boot_disk_size_gib"
     */
    public function testPropertyBootDiskSizeGib()
    {
    }

    /**
     * Test attribute "cpu_model"
     */
    public function testPropertyCpuModel()
    {
    }

    /**
     * Test attribute "create_by"
     */
    public function testPropertyCreateBy()
    {
    }

    /**
     * Test attribute "datacenter_id"
     */
    public function testPropertyDatacenterId()
    {
    }

    /**
     * Test attribute "external_ip_address"
     */
    public function testPropertyExternalIpAddress()
    {
    }

    /**
     * Test attribute "gpu_model"
     */
    public function testPropertyGpuModel()
    {
    }

    /**
     * Test attribute "gpu_quantity"
     */
    public function testPropertyGpuQuantity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "image_id"
     */
    public function testPropertyImageId()
    {
    }

    /**
     * Test attribute "image_name"
     */
    public function testPropertyImageName()
    {
    }

    /**
     * Test attribute "init_state"
     */
    public function testPropertyInitState()
    {
    }

    /**
     * Test attribute "internal_ip_address"
     */
    public function testPropertyInternalIpAddress()
    {
    }

    /**
     * Test attribute "lcm_state"
     */
    public function testPropertyLcmState()
    {
    }

    /**
     * Test attribute "machine_type"
     */
    public function testPropertyMachineType()
    {
    }

    /**
     * Test attribute "memory"
     */
    public function testPropertyMemory()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "nics"
     */
    public function testPropertyNics()
    {
    }

    /**
     * Test attribute "one_state"
     */
    public function testPropertyOneState()
    {
    }

    /**
     * Test attribute "price_hr"
     */
    public function testPropertyPriceHr()
    {
    }

    /**
     * Test attribute "private_image_id"
     */
    public function testPropertyPrivateImageId()
    {
    }

    /**
     * Test attribute "public_image_id"
     */
    public function testPropertyPublicImageId()
    {
    }

    /**
     * Test attribute "public_image_name"
     */
    public function testPropertyPublicImageName()
    {
    }

    /**
     * Test attribute "public_ip_address"
     */
    public function testPropertyPublicIpAddress()
    {
    }

    /**
     * Test attribute "region_id"
     */
    public function testPropertyRegionId()
    {
    }

    /**
     * Test attribute "region_name"
     */
    public function testPropertyRegionName()
    {
    }

    /**
     * Test attribute "renewable_energy"
     */
    public function testPropertyRenewableEnergy()
    {
    }

    /**
     * Test attribute "rules"
     */
    public function testPropertyRules()
    {
    }

    /**
     * Test attribute "security_group_ids"
     */
    public function testPropertySecurityGroupIds()
    {
    }

    /**
     * Test attribute "short_state"
     */
    public function testPropertyShortState()
    {
    }

    /**
     * Test attribute "storage_disks"
     */
    public function testPropertyStorageDisks()
    {
    }

    /**
     * Test attribute "vcpus"
     */
    public function testPropertyVcpus()
    {
    }

    /**
     * Test attribute "vm_state"
     */
    public function testPropertyVmState()
    {
    }
}
