<?php
/**
 * BillingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BillingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BillingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createBillingAccount
     *
     * Create a billing account.
     *
     */
    public function testCreateBillingAccount()
    {
    }

    /**
     * Test case for deleteBillingAccount
     *
     * Delete billing account.
     *
     */
    public function testDeleteBillingAccount()
    {
    }

    /**
     * Test case for getBillingAccount
     *
     * Get a billing account.
     *
     */
    public function testGetBillingAccount()
    {
    }

    /**
     * Test case for getBillingAccountDetails
     *
     * Get billing account details.
     *
     */
    public function testGetBillingAccountDetails()
    {
    }

    /**
     * Test case for getBillingAccountPaymentMethods
     *
     * Get payment methods.
     *
     */
    public function testGetBillingAccountPaymentMethods()
    {
    }

    /**
     * Test case for getBillingAccountSetupIntent
     *
     * Get setup intent.
     *
     */
    public function testGetBillingAccountSetupIntent()
    {
    }

    /**
     * Test case for getBillingAccountSpendDetails
     *
     * Get spend details.
     *
     */
    public function testGetBillingAccountSpendDetails()
    {
    }

    /**
     * Test case for getBillingAccountStripeInvoices
     *
     * Get invoices.
     *
     */
    public function testGetBillingAccountStripeInvoices()
    {
    }

    /**
     * Test case for listBillingAccounts
     *
     * List billing accounts.
     *
     */
    public function testListBillingAccounts()
    {
    }

    /**
     * Test case for listOutstandingStripeInvoices
     *
     * Get outstanding invoices.
     *
     */
    public function testListOutstandingStripeInvoices()
    {
    }

    /**
     * Test case for removeBillingAccountPaymentMethod
     *
     * Remove payment method.
     *
     */
    public function testRemoveBillingAccountPaymentMethod()
    {
    }

    /**
     * Test case for setBillingAccountDefaultPaymentMethod
     *
     * Set default payment method.
     *
     */
    public function testSetBillingAccountDefaultPaymentMethod()
    {
    }

    /**
     * Test case for updateBillingAccount
     *
     * Update billing account.
     *
     */
    public function testUpdateBillingAccount()
    {
    }
}
