<?php
/**
 * DisksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DisksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DisksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachStorageDisk
     *
     * Attach storage disk to VM.
     *
     */
    public function testAttachStorageDisk()
    {
    }

    /**
     * Test case for createDiskSnapshot
     *
     * Create Disk Snapshot.
     *
     */
    public function testCreateDiskSnapshot()
    {
    }

    /**
     * Test case for createStorageDisk
     *
     * Create storage disk.
     *
     */
    public function testCreateStorageDisk()
    {
    }

    /**
     * Test case for deleteDiskSnapshot
     *
     * Delete Disk Snapshots.
     *
     */
    public function testDeleteDiskSnapshot()
    {
    }

    /**
     * Test case for deleteStorageDisk
     *
     * Delete storage disk.
     *
     */
    public function testDeleteStorageDisk()
    {
    }

    /**
     * Test case for detachStorageDisk
     *
     * Detach storage disk from VM.
     *
     */
    public function testDetachStorageDisk()
    {
    }

    /**
     * Test case for getDisk
     *
     * List disks.
     *
     */
    public function testGetDisk()
    {
    }

    /**
     * Test case for listDiskSnapshots
     *
     * List Disk Snapshots.
     *
     */
    public function testListDiskSnapshots()
    {
    }

    /**
     * Test case for listDisks
     *
     * List disks.
     *
     */
    public function testListDisks()
    {
    }

    /**
     * Test case for revertDisk
     *
     * Revert Disk to Snapshot.
     *
     */
    public function testRevertDisk()
    {
    }
}
