<?php
/**
 * PermissionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PermissionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PermissionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addBillingAccountUserPermission
     *
     * Add billing account user.
     *
     */
    public function testAddBillingAccountUserPermission()
    {
    }

    /**
     * Test case for addDataCenterUserPermission
     *
     * Add data center user.
     *
     */
    public function testAddDataCenterUserPermission()
    {
    }

    /**
     * Test case for addProjectUserPermission
     *
     * Add project user.
     *
     */
    public function testAddProjectUserPermission()
    {
    }

    /**
     * Test case for listUserPermissions
     *
     * List.
     *
     */
    public function testListUserPermissions()
    {
    }

    /**
     * Test case for removeBillingAccountUserPermission
     *
     * Remove billing account user.
     *
     */
    public function testRemoveBillingAccountUserPermission()
    {
    }

    /**
     * Test case for removeDataCenterUserPermission
     *
     * Remove data center user.
     *
     */
    public function testRemoveDataCenterUserPermission()
    {
    }

    /**
     * Test case for removeProjectUserPermission
     *
     * Remove project user.
     *
     */
    public function testRemoveProjectUserPermission()
    {
    }
}
