<?php
/**
 * ProjectsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProjectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProjectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createProject
     *
     * Create.
     *
     */
    public function testCreateProject()
    {
    }

    /**
     * Test case for deleteProject
     *
     * Delete.
     *
     */
    public function testDeleteProject()
    {
    }

    /**
     * Test case for getProject
     *
     * Get.
     *
     */
    public function testGetProject()
    {
    }

    /**
     * Test case for listProjectSshKeys
     *
     * List SSH keys.
     *
     */
    public function testListProjectSshKeys()
    {
    }

    /**
     * Test case for listProjects
     *
     * List.
     *
     */
    public function testListProjects()
    {
    }

    /**
     * Test case for updateProject
     *
     * Update.
     *
     */
    public function testUpdateProject()
    {
    }
}
