<?php
/**
 * VirtualMachinesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Cudo Compute service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.57
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * VirtualMachinesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VirtualMachinesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for attachSecurityGroup
     *
     * Attach security group to VM.
     *
     */
    public function testAttachSecurityGroup()
    {
    }

    /**
     * Test case for connectVM
     *
     * Connect via VNC.
     *
     */
    public function testConnectVM()
    {
    }

    /**
     * Test case for countVMs
     *
     * Count.
     *
     */
    public function testCountVMs()
    {
    }

    /**
     * Test case for createPrivateVMImage
     *
     * Create private VM image.
     *
     */
    public function testCreatePrivateVMImage()
    {
    }

    /**
     * Test case for createVM
     *
     * Create virtual machine.
     *
     */
    public function testCreateVM()
    {
    }

    /**
     * Test case for deletePrivateVMImage
     *
     * Delete private VM image.
     *
     */
    public function testDeletePrivateVMImage()
    {
    }

    /**
     * Test case for detachSecurityGroup
     *
     * Attach security group to VM.
     *
     */
    public function testDetachSecurityGroup()
    {
    }

    /**
     * Test case for getPrivateVMImage
     *
     * Get private VM image.
     *
     */
    public function testGetPrivateVMImage()
    {
    }

    /**
     * Test case for getVM
     *
     * Get.
     *
     */
    public function testGetVM()
    {
    }

    /**
     * Test case for listPrivateVMImages
     *
     * List private VM images.
     *
     */
    public function testListPrivateVMImages()
    {
    }

    /**
     * Test case for listPublicVMImages
     *
     * List public VM images.
     *
     */
    public function testListPublicVMImages()
    {
    }

    /**
     * Test case for listVMDataCenters
     *
     * List data centers.
     *
     */
    public function testListVMDataCenters()
    {
    }

    /**
     * Test case for listVMDisks
     *
     * List disks attached to VM.
     *
     */
    public function testListVMDisks()
    {
    }

    /**
     * Test case for listVMMachineTypes
     *
     * List machine types.
     *
     */
    public function testListVMMachineTypes()
    {
    }

    /**
     * Test case for listVMs
     *
     * List.
     *
     */
    public function testListVMs()
    {
    }

    /**
     * Test case for monitorVM
     *
     * Monitor.
     *
     */
    public function testMonitorVM()
    {
    }

    /**
     * Test case for rebootVM
     *
     * Reboot.
     *
     */
    public function testRebootVM()
    {
    }

    /**
     * Test case for resizeVM
     *
     * Resize vCPU and memory of VM.
     *
     */
    public function testResizeVM()
    {
    }

    /**
     * Test case for resizeVMDisk
     *
     * Resize a VM's disk.
     *
     */
    public function testResizeVMDisk()
    {
    }

    /**
     * Test case for startVM
     *
     * Start.
     *
     */
    public function testStartVM()
    {
    }

    /**
     * Test case for stopVM
     *
     * Stop.
     *
     */
    public function testStopVM()
    {
    }

    /**
     * Test case for terminateVM
     *
     * Terminate.
     *
     */
    public function testTerminateVM()
    {
    }

    /**
     * Test case for updatePrivateVMImage
     *
     * Update private VM image.
     *
     */
    public function testUpdatePrivateVMImage()
    {
    }

    /**
     * Test case for updateVMMetadata
     *
     * Update VM metadata.
     *
     */
    public function testUpdateVMMetadata()
    {
    }
}
